spring:
  datasource:
    url: jdbc:postgresql://dpg-d7o6f237uimc73blhpk0-a.oregon-postgres.render.com/game_20j1
    username: game_20j1_user
    password: tyzlBgbLXHlCLmZH6yCGJAROASNytrxw
    
    
    
    
    
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # 开发用：自动建表
    show-sql: true       # 控制台打印SQL

server:
  port: 8080
