spring:
  datasource:
    url: jdbc:postgresql://dpg-d7goigu7r5hc73dorib0-a.oregon-postgres.render.com/games_j38e
    username: games_j38e_user
    password: 1OEDQ3qqWcWp2I7aZZdQ5y1M9vP1rlQC
    
    
    
    
    
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # 开发用：自动建表
    show-sql: true       # 控制台打印SQL

server:
  port: 8080